spring:
  profiles.active: Deepak
---
server:
  port: 8082
  
spring:
    profiles: Deepak
    datasource:
        url: jdbc:mysql://localhost:3306/demo
        username: root
        password: p@ssword
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
            ddl-auto: update
management:
  server:
    port: 9001